---
ansible_ssh_user: root

static_web:
  hostname: www.dreisbach.us
  host_aliases:
    - dreisbach.us
  webroot: /var/www/static_web

homebase:
  user: homebase
  root: /opt/homebase/
  authorized_keys:
    - https://github.com/cndreisbach.keys
  hostname: "{{ ansible_fqdn }}"
