---
- name: Install MySQL server
  apt: name={{ item }} state=present
  with_items:
    - mysql-server
    - python-mysqldb
- name: Create root my.cnf
  template: src=my.cnf.j2 dest=/root/.my.cnf    
- name: Sets the MySQL root password 
  mysql_user: user=root password="{{ secret.mysql_root_password }}" host=localhost
- name: Deletes anonymous MySQL server user for ansible_fqdn
  mysql_user: user="" host="{{ ansible_fqdn }}" state="absent"
- name: Deletes anonymous MySQL server user for localhost
  mysql_user: user="" state="absent"
- name: Secures the MySQL root user for IPV6 localhost (::1)
  mysql_user: user="root" password="{{ secret.mysql_root_password }}" host="::1"
- name: Secures the MySQL root user for IPV4 localhost (127.0.0.1)
  mysql_user: user="root" password="{{ secret.mysql_root_password }}" host="127.0.0.1"
- name: Secures the MySQL root user for localhost domain (localhost)
  mysql_user: user="root" password="{{ secret.mysql_root_password }}" host="localhost"
- name: Secures the MySQL root user for server_hostname domain
  mysql_user: user="root" password="{{ secret.mysql_root_password }}" host="{{ ansible_fqdn }}"  
- name: Removes the MySQL test database
  mysql_db: db=test state=absent  
- name: Make sure MySQL is running
  service: name=mysql enabled=yes state=started